import express from "express";import session from "express-session";import bcrypt from "bcryptjs";import Database from "better-sqlite3";import nodemailer from "nodemailer";import dotenv from "dotenv";import path from "path";import{fileURLToPath}from"url";dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),db=new Database(path.join(__dirname,"../grim.db"));
app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||"CHANGE-ME",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",maxAge:2592000000}}));app.use(express.static(path.join(__dirname,"../public")));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,email TEXT UNIQUE,password_hash TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,user_id INTEGER,name TEXT,email TEXT,phone TEXT,address TEXT,items_json TEXT,total INTEGER,status TEXT DEFAULT 'new',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS support_tickets(id INTEGER PRIMARY KEY,topic TEXT,name TEXT,email TEXT,order_ref TEXT,message TEXT,status TEXT DEFAULT 'open',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS newsletter(id INTEGER PRIMARY KEY,email TEXT UNIQUE,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const products=[{id:1,name:"GRIM Design 01",price:18000,color:"RAV’KAEL"},{id:2,name:"GRIM Design 02",price:18000,color:"RAV’KAEL"},{id:3,name:"GRIM Design 03",price:18000,color:"RAV’KAEL"},{id:4,name:"GRIM Design 04",price:18000,color:"RAV’KAEL"},{id:5,name:"GRIM Design 05",price:18000,color:"RAV’KAEL"},{id:6,name:"GRIM Design 06",price:18000,color:"RAV’KAEL"},{id:7,name:"GRIM Design 07",price:18000,color:"RAV’KAEL"},{id:8,name:"GRIM Design 08",price:18000,color:"RAV’KAEL"},{id:9,name:"GRIM Design 09",price:18000,color:"RAV’KAEL"},{id:10,name:"GRIM Design 10",price:18000,color:"RAV’KAEL"},{id:11,name:"GRIM Design 11",price:18000,color:"RAV’KAEL"},{id:12,name:"GRIM Design 12",price:18000,color:"RAV’KAEL"},{id:13,name:"GRIM Design 13",price:18000,color:"RAV’KAEL"},{id:14,name:"GRIM Design 14",price:18000,color:"RAV’KAEL"},{id:15,name:"GRIM Design 15",price:18000,color:"RAV’KAEL"},{id:16,name:"GRIM Design 16",price:18000,color:"RAV’KAEL"},{id:17,name:"GRIM Design 17",price:18000,color:"RAV’KAEL"},{id:18,name:"GRIM Design 18",price:18000,color:"RAV’KAEL"},{id:19,name:"GRIM Design 19",price:18000,color:"RAV’KAEL"},{id:20,name:"GRIM Design 20",price:18000,color:"RAV’KAEL"},{id:21,name:"GRIM Design 21",price:18000,color:"RAV’KAEL"},{id:22,name:"GRIM Design 22",price:18000,color:"RAV’KAEL"},{id:23,name:"GRIM Design 23",price:18000,color:"RAV’KAEL"},{id:24,name:"GRIM Design 24",price:18000,color:"RAV’KAEL"},{id:25,name:"GRIM Design 25",price:18000,color:"RAV’KAEL"},{id:26,name:"GRIM Design 26",price:18000,color:"RAV’KAEL"}];
app.get("/api/products",(q,s)=>s.json(products));
app.get("/api/market",(q,s)=>{let raw=String(q.headers["cf-ipcountry"]||q.headers["x-vercel-ip-country"]||q.headers["x-country-code"]||"").toUpperCase();s.json({country:/^[A-Z]{2}$/.test(raw)?raw:null})});app.get("/api/me",(q,s)=>s.json(q.session.user||null));
app.post("/api/register",async(q,s)=>{let{name,email,password}=q.body||{};if(!name||!email||!password||password.length<6)return s.status(400).json({error:"Complete all fields."});try{let hash=await bcrypt.hash(password,12),r=db.prepare("INSERT INTO users(name,email,password_hash) VALUES(?,?,?)").run(name,email.toLowerCase(),hash);q.session.user={id:r.lastInsertRowid,name,email:email.toLowerCase()};s.json(q.session.user)}catch(e){s.status(400).json({error:"That email is already registered."})}});
app.post("/api/login",async(q,s)=>{let{email,password}=q.body||{},u=db.prepare("SELECT * FROM users WHERE email=?").get((email||"").toLowerCase());if(!u||!await bcrypt.compare(password||"",u.password_hash))return s.status(401).json({error:"Incorrect email or password."});q.session.user={id:u.id,name:u.name,email:u.email};s.json(q.session.user)});
async function notify(o){if(!process.env.SMTP_HOST||!process.env.STORE_OWNER_EMAIL)return;let t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:+(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}),lines=o.items.map(x=>`${x.name} / ${x.color} / Size ${x.size||"M"} / Qty ${x.qty} / ₦${(x.price*x.qty).toLocaleString()}`).join("\n");await t.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:process.env.STORE_OWNER_EMAIL,subject:`NEW GRIM ORDER #${o.id}`,text:`Customer: ${o.name}\nEmail: ${o.email}\nPhone: ${o.phone}\nAddress: ${o.address}\n\n${lines}\n\nTOTAL ₦${o.total.toLocaleString()}`})}
app.post("/api/orders",async(q,s)=>{let{name,email,phone,address,items,country,currency}=q.body||{};if(!name||!email||!phone||!address||!items?.length)return s.status(400).json({error:"Complete checkout details."});let clean=[],total=0;for(let x of items){let p=products.find(v=>v.id===+x.id),qty=Math.max(1,Math.min(10,+x.qty||1));if(p){clean.push({...p,qty,size:String(x.size||"M").slice(0,4)});total+=p.price*qty}}let r=db.prepare("INSERT INTO orders(user_id,name,email,phone,address,items_json,total) VALUES(?,?,?,?,?,?,?)").run(q.session.user?.id||null,name,email,phone,address,JSON.stringify(clean),total),o={id:+r.lastInsertRowid,name,email,phone,address,items:clean,total};try{await notify(o)}catch(e){console.error(e)}s.json({ok:true,orderId:o.id,total,country:country||"NG",currency:currency||"NGN"})});

app.post("/api/support",async(q,s)=>{let{topic,name,email,order,message}=q.body||{};if(!topic||!name||!email||!message)return s.status(400).json({error:"Complete the required fields."});let r=db.prepare("INSERT INTO support_tickets(topic,name,email,order_ref,message) VALUES(?,?,?,?,?)").run(String(topic).slice(0,80),String(name).slice(0,100),String(email).slice(0,160),String(order||"").slice(0,50),String(message).slice(0,3000));if(process.env.SMTP_HOST&&process.env.STORE_OWNER_EMAIL){try{let t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:+(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await t.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:process.env.STORE_OWNER_EMAIL,replyTo:email,subject:`GRIM CUSTOMER CARE #${r.lastInsertRowid} — ${topic}`,text:`Name: ${name}\nEmail: ${email}\nOrder: ${order||"N/A"}\nTopic: ${topic}\n\n${message}`})}catch(e){console.error(e)}}s.json({ok:true,ticketId:r.lastInsertRowid})});
app.post("/api/newsletter",(q,s)=>{let email=String(q.body?.email||"").trim().toLowerCase();if(!email||!email.includes("@"))return s.status(400).json({error:"Enter a valid email."});try{db.prepare("INSERT INTO newsletter(email) VALUES(?)").run(email)}catch(e){}s.json({ok:true})});
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"../public/index.html")));app.listen(process.env.PORT||3000,()=>console.log("GRIM STORE RUNNING"));