import express from "express";import session from "express-session";import bcrypt from "bcryptjs";import Database from "better-sqlite3";import nodemailer from "nodemailer";import dotenv from "dotenv";import path from "path";import{fileURLToPath}from"url";dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),db=new Database(path.join(__dirname,"../grim.db"));
app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||"CHANGE-ME",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",maxAge:2592000000}}));app.use(express.static(path.join(__dirname,"../public")));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,email TEXT UNIQUE,password_hash TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY,user_id INTEGER,name TEXT,email TEXT,phone TEXT,address TEXT,items_json TEXT,total INTEGER,status TEXT DEFAULT 'new',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const products=[{id:1,name:"GRIM Tee",price:18000,color:"Obsidian"},{id:2,name:"GRIM Tee",price:18000,color:"Veil"},{id:3,name:"GRIM Sweat Jacket",price:20000,color:"Bloodline"},{id:4,name:"GRIM Hoodie",price:28000,color:"Abyss"},{id:5,name:"GRIM Hoodie",price:28000,color:"Rose Reaper"},{id:6,name:"GRIM Hoodie",price:28000,color:"Void Violet"},{id:7,name:"GRIM Wear",price:48000,color:"Obsidian"}];
app.get("/api/products",(q,s)=>s.json(products));app.get("/api/me",(q,s)=>s.json(q.session.user||null));
app.post("/api/register",async(q,s)=>{let{name,email,password}=q.body||{};if(!name||!email||!password||password.length<6)return s.status(400).json({error:"Complete all fields."});try{let hash=await bcrypt.hash(password,12),r=db.prepare("INSERT INTO users(name,email,password_hash) VALUES(?,?,?)").run(name,email.toLowerCase(),hash);q.session.user={id:r.lastInsertRowid,name,email:email.toLowerCase()};s.json(q.session.user)}catch(e){s.status(400).json({error:"That email is already registered."})}});
app.post("/api/login",async(q,s)=>{let{email,password}=q.body||{},u=db.prepare("SELECT * FROM users WHERE email=?").get((email||"").toLowerCase());if(!u||!await bcrypt.compare(password||"",u.password_hash))return s.status(401).json({error:"Incorrect email or password."});q.session.user={id:u.id,name:u.name,email:u.email};s.json(q.session.user)});
async function notify(o){if(!process.env.SMTP_HOST||!process.env.STORE_OWNER_EMAIL)return;let t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:+(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}),lines=o.items.map(x=>`${x.name} / ${x.color} / Qty ${x.qty} / ₦${(x.price*x.qty).toLocaleString()}`).join("\n");await t.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:process.env.STORE_OWNER_EMAIL,subject:`NEW GRIM ORDER #${o.id}`,text:`Customer: ${o.name}\nEmail: ${o.email}\nPhone: ${o.phone}\nAddress: ${o.address}\n\n${lines}\n\nTOTAL ₦${o.total.toLocaleString()}`})}
app.post("/api/orders",async(q,s)=>{let{name,email,phone,address,items}=q.body||{};if(!name||!email||!phone||!address||!items?.length)return s.status(400).json({error:"Complete checkout details."});let clean=[],total=0;for(let x of items){let p=products.find(v=>v.id===+x.id),qty=Math.max(1,Math.min(10,+x.qty||1));if(p){clean.push({...p,qty});total+=p.price*qty}}let r=db.prepare("INSERT INTO orders(user_id,name,email,phone,address,items_json,total) VALUES(?,?,?,?,?,?,?)").run(q.session.user?.id||null,name,email,phone,address,JSON.stringify(clean),total),o={id:+r.lastInsertRowid,name,email,phone,address,items:clean,total};try{await notify(o)}catch(e){console.error(e)}s.json({ok:true,orderId:o.id,total})});
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"../public/index.html")));app.listen(process.env.PORT||3000,()=>console.log("GRIM STORE RUNNING"));